urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^post(?P<blog_id>[0-9]+)/$',views.b_detail,name='b_detail'),
	# url(r'like/$', views.like_product, name='dict'),
    url(r'blogform/$', views.create_blog, name='blogform'),
    url(r'comment/$', views.comment_product, name='comment'),
]

models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models


class blog(models.Model):
    title = models.CharField(max_length=255)
    image = models.FileField(upload_to='pic/', blank=True, null=True)
    short_desc = models.CharField(max_length=150, blank=True, null=True)
    content = RichTextUploadingField()
    create_date = models.DateTimeField(auto_now_add=True)
    comment = models.PositiveIntegerField(default=0, blank=True, null=True)

    def __str__(self):
        return self.title


class Comment_block(models.Model):
		info = models.ForeignKey(blog)
		name = models.CharField(max_length=20, null=True, blank=True)
		comment = models.CharField(max_length=500)
		user = models.CharField(max_length=20, null=True, blank=True)

forms.py
from django import forms
from .models import blog

class blogForm(forms.Form):
    title = forms.CharField(label="title")
    image = forms.FileField(label="image")
    content = forms.CharField(label="content")
    create_date = forms.DateTimeField(label="date")

views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from .forms import blogForm
from django.shortcuts import render,get_object_or_404

# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from .models import blog, Comment_block

def index(request):
    category_list = blog.objects.all()
    context = {'category_list': category_list}
    return render(request, 'blog/index.html', context)

def b_detail(request, blog_id):
    content = get_object_or_404(blog, pk=blog_id)
    comments = Comment_block.objects.filter(name__contains=blog_id)
    return render(request, 'blog/post.html', {'blog': content,'comments':comments, 'error_message': "You didn't select a choice.",})


def comment_product(request):
    if request.method == 'POST':
        commentid = request.POST['commentid']
        comment = request.POST['comment']
        commentname = request.POST['commentname']
        print(commentid);
        print(comment);
        print(commentname);

        c = get_object_or_404(blog, pk=commentid)
        c.comment += 1
        c.save()

        Comment_block.objects.create(
            info_id = commentid,
            name = commentid,
            user=commentname,
            comment = comment,
        )

        returncomments = {
            comment, commentid, commentname
        }
        return HttpResponse(returncomments)

# @login_required
def create_blog(request):
    # Handle file upload
    if request.method == 'POST':
        form = blogForm(request.POST, request.FILES)
        if form.is_valid():
            newdoc = blog(title = request.POST['title'],content = request.POST['content'], create_date = request.POST['create_date'], image = request.FILES['image'] )

            newdoc.save()

            # Redirect to the document list after POST
            return HttpResponseRedirect('/blog/blogform/')
    else:
        form = blogForm() # A empty, unbound form

    return render(request, 'blog/blogform.html', {'form': form},

    )

templates/blog/blogform.html
<!DOCTYPE html>
<html>
<head>

      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <link rel="shortcut icon" href="/media/pic/logo.png" />
      <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AIC BIMTECH: Business Incubator, Coworking in Greater Noida supported by Niti Aayog and Uttar Pradesh Government</title>
  <style>
  body{background:#ff0000;margin:0}
.form{width:1200px;height:auto;background:#e6e6e6;border-radius:8px;box-shadow:0 0 40px -10px #000;margin:calc(39vh - 220px) auto;padding:20px 30px;max-width:calc(100vw - 40px);box-sizing:border-box;font-family:'Montserrat',sans-serif;position:relative}
h2{margin:10px 0;padding-bottom:10px;width:180px;color:#78788c;border-bottom:3px solid #78788c}
input{width:100%;padding:10px;box-sizing:border-box;background:none;outline:none;resize:none;border:0;font-family:'Montserrat',sans-serif;transition:all .3s;border-bottom:2px solid #bebed2}
input:focus{border-bottom:2px solid #78788c}
p:before{content:attr(type);display:block;margin:28px 0 0;font-size:14px;color:#5a5a5a}
button{float:right;padding:8px 12px;margin:8px 0 0;font-family:'Montserrat',sans-serif;border:2px solid #78788c;background:0;color:#5a5a6e;cursor:pointer;transition:all .3s}
button:hover{background:#78788c;color:#fff}
div{content:'Hi';position:absolute;bottom:-15px;right:-20px;background:#50505a;color:#fff;width:320px;padding:16px 4px 16px 0;border-radius:6px;font-size:13px;box-shadow:10px 10px 40px -14px #000}
span{margin:0 5px 0 15px}
.submit{
  cursor:pointer;border-radius:20px;background:#cecece;font-weight: 700;
}
.submit:hover{
  background: #6d6d6d;
  color:#fff;
}
  </style>

  <script src="https://cdn.ckeditor.com/4.9.2/standard/ckeditor.js"></script>

</head>
<body>


  <form class="form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
  <h2>Write Your Blog</h2>
  <p for="id_title"> Title<input type="text" name="title" required="" id="id_title"></p>
  <p for="id_image">image<input type="file" name="image" required="" id="id_image"></p>
  <p for="id_content">Description<input type="text" name="editor1" required="" id="id_content"></p>
  <p for="id_create_date">Date<input type="text" name="create_date" required="" id="id_create_date"></p>
<input type="submit" class="submit">

</form>
		<script>
			CKEDITOR.replace( 'editor1' );
		</script>

</body>
</html>

templates/blog/comment.html
hello

templates/blog/login.html
<!-- <h2>Login</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Login</button>
</form> -->